/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payrollsystemnew.view.payment;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import payrollsystemnew.controller.AttendanceController;
import payrollsystemnew.controller.EmployeeController;
import payrollsystemnew.controller.GradeController;
import payrollsystemnew.controller.PaymentController;
import payrollsystemnew.model.Damage;
import payrollsystemnew.model.Employee;
import payrollsystemnew.model.Grade;
import payrollsystemnew.model.LeaveCount;
import payrollsystemnew.model.Loan;
import payrollsystemnew.model.LoanPayment;
import payrollsystemnew.model.Salary;
import payrollsystemnew.model.SalaryAdvance;
import payrollsystemnew.model.SalaryPayment;
import payrollsystemnew.other.IDGenerator;

/**
 *
 * @author User
 */
public class SalaryPaymentPanel extends javax.swing.JPanel {
    private SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
    public static SalaryPaymentPanel paymentPanel;
    public static String employeeID;
    double halfDayRate=30;
    double stampFee=25;
    double taxPercentage=0.05;
    boolean b=false;
    String lastDay=null;
    String lastMonthLastDay=null;
    /**
     * Creates new form employeePanel
     */
    public SalaryPaymentPanel() {
        initComponents();
        SimpleDateFormat monthFormat=new SimpleDateFormat("MM");
        int monthIndex=Integer.parseInt(monthFormat.format(new Date()))-1;
        monthNameCombo.setSelectedIndex(monthIndex);
        paymentPanel=this;
        try {
            fillemployeeIDCombo();
            fillYearCombo();
        } catch (ClassNotFoundException | SQLException | ParseException ex) {
            Logger.getLogger(SalaryPaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        saveButton.setEnabled(false);
        printButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        accNumberText = new javax.swing.JTextField();
        employeeIDCombo = new javax.swing.JComboBox();
        paymentTypeCombo = new javax.swing.JComboBox();
        monthNameCombo = new javax.swing.JComboBox();
        bankNameText = new javax.swing.JTextField();
        yearIDCombo = new javax.swing.JComboBox();
        viewButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        basicSalaryText = new javax.swing.JTextField();
        otAmountText = new javax.swing.JTextField();
        epfEmployerText = new javax.swing.JTextField();
        etfEmployerText = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        bonusAmountText = new javax.swing.JTextField();
        manageBonusButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        totalEarningsText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        epfEmployeeText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        stampFeeText = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        taxAmountText = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        advanceSalaryText = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        loanAmountText = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        noPayAmountText = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        totalDeductionText = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        halfDayAmountText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        damagesText = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        netAmountText = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Info.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), java.awt.Color.white)); // NOI18N
        jPanel5.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Employee ID :");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Name :");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Bank :");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Year :");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Month :");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Payment Type :");

        nameText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        accNumberText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        accNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accNumberTextActionPerformed(evt);
            }
        });

        employeeIDCombo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        employeeIDCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                employeeIDComboItemStateChanged(evt);
            }
        });

        paymentTypeCombo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        monthNameCombo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        monthNameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "Aprill", "May", "June", "July", "August", "September", "Octomber", "November", "December" }));

        bankNameText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        yearIDCombo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        viewButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(employeeIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(bankNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(yearIDCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(monthNameCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 111, Short.MAX_VALUE)))
                .addGap(53, 53, 53))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(employeeIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(paymentTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Earnings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Basic Salary :");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("OT Earning :");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("EPF(Employer) :");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("ETF(Employer) :");

        basicSalaryText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        otAmountText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        epfEmployerText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        etfEmployerText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Bonus :");

        bonusAmountText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        manageBonusButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        manageBonusButton.setText("Manage Bonus");
        manageBonusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBonusButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Total Earnings :");

        totalEarningsText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(epfEmployerText, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etfEmployerText, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalEarningsText, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(manageBonusButton))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(otAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(basicSalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bonusAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(52, 52, 52))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(basicSalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(otAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(bonusAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(manageBonusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(totalEarningsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(epfEmployerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(etfEmployerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Deductions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), java.awt.Color.white)); // NOI18N
        jPanel4.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("EPF(Employee) :");

        epfEmployeeText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Stamp Fee :");

        stampFeeText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Tax :");

        taxAmountText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Salary Advance :");

        advanceSalaryText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Loans :");

        loanAmountText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("No Pay Leaves :");

        noPayAmountText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Total Deductions :");

        totalDeductionText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("Half Day :");

        halfDayAmountText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("Damages :");

        damagesText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(epfEmployeeText)
                        .addComponent(stampFeeText)
                        .addComponent(taxAmountText)
                        .addComponent(advanceSalaryText)
                        .addComponent(loanAmountText)
                        .addComponent(noPayAmountText)
                        .addComponent(halfDayAmountText)
                        .addComponent(damagesText, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(totalDeductionText, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(epfEmployeeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(stampFeeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(taxAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(advanceSalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(loanAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noPayAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(halfDayAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(damagesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(totalDeductionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Net Amount :");

        netAmountText.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        netAmountText.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        saveButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        printButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(75, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(netAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(netAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(printButton)
                            .addComponent(saveButton))))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystemnew/images/Background.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void employeeIDComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_employeeIDComboItemStateChanged
        b=false;
        employeeID=employeeIDCombo.getSelectedItem().toString();
        bonusAmountText.setText("");
        try {
            ResultSet rst=EmployeeController.getAllEmployees_PaymentDetails(employeeIDCombo.getSelectedItem().toString());
            while(rst.next()){
                nameText.setText(rst.getString(2)+" "+rst.getString(3));
                bankNameText.setText(rst.getString(4));
                accNumberText.setText(rst.getString(5));
                paymentTypeCombo.removeAllItems();
                if("1".equals(rst.getString(6))){
                    paymentTypeCombo.addItem("Cash");
                }
                if("1".equals(rst.getString(7))){
                    paymentTypeCombo.addItem("Cheque");
                }
                if("1".equals(rst.getString(8))){
                    paymentTypeCombo.addItem("Deposit");
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SalaryPaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_employeeIDComboItemStateChanged

    private void manageBonusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBonusButtonActionPerformed
        new ViewEmployeeBonusForm().setVisible(true);

    }//GEN-LAST:event_manageBonusButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        try {
            viewSalaryDetails();
        } catch (ParseException | SQLException | ClassNotFoundException ex) {
            Logger.getLogger(SalaryPaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_viewButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            String SalaryID=IDGenerator.getNewID("salary", "salaryID", "S");
            String epfAmount=Double.toString(Double.parseDouble(epfEmployeeText.getText())+Double.parseDouble(epfEmployerText.getText()));
            int rowCount1=PaymentController.addSalary(new Salary(SalaryID, employeeIDCombo.getSelectedItem().toString(), basicSalaryText.getText(), otAmountText.getText(), bonusAmountText.getText(), stampFeeText.getText(), taxAmountText.getText(), advanceSalaryText.getText(), loanAmountText.getText(), noPayAmountText.getText(), halfDayAmountText.getText(), damagesText.getText(), epfAmount, etfEmployerText.getText()));
            int rowCount2=PaymentController.addSalaryPayment(new SalaryPayment(SalaryID, paymentTypeCombo.getSelectedItem().toString(),lastDay ,Double.parseDouble(netAmountText.getText())));
            if(rowCount1>0 && rowCount2>0){
                JOptionPane.showMessageDialog(this, "Salary detail added successfully.");
                ArrayList<Loan> loanList=PaymentController.searchProcessingLoan(employeeIDCombo.getSelectedItem().toString());
                for(Loan loan : loanList){
                    PaymentController.loanPayment(new LoanPayment(loan.getLoanID(), lastDay, loan.getMonthlyIntallment()));
                    if(PaymentController.getPaidLoanAmount(loan.getLoanID())>=loan.getMonthlyIntallment()*loan.getInstallment()){
                        int rowCount=PaymentController.markLoanPaymentOver(loan.getLoanID());
                        if(rowCount>0){
                            JOptionPane.showMessageDialog(this, loan.getLoanID()+" payment is over.");
                        }
                    }
                }
                //printReport();
            }else{
                JOptionPane.showMessageDialog(this, "Salary detail addition failed.");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SalaryPaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void accNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accNumberTextActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try {
            printReport();
        } catch (JRException ex) {
            Logger.getLogger(SalaryPaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accNumberText;
    private javax.swing.JTextField advanceSalaryText;
    private javax.swing.JTextField bankNameText;
    private javax.swing.JTextField basicSalaryText;
    private javax.swing.JTextField bonusAmountText;
    private javax.swing.JTextField damagesText;
    private javax.swing.JComboBox employeeIDCombo;
    private javax.swing.JTextField epfEmployeeText;
    private javax.swing.JTextField epfEmployerText;
    private javax.swing.JTextField etfEmployerText;
    private javax.swing.JTextField halfDayAmountText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField loanAmountText;
    private javax.swing.JButton manageBonusButton;
    private javax.swing.JComboBox monthNameCombo;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField netAmountText;
    private javax.swing.JTextField noPayAmountText;
    private javax.swing.JTextField otAmountText;
    private javax.swing.JComboBox paymentTypeCombo;
    private javax.swing.JButton printButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField stampFeeText;
    private javax.swing.JTextField taxAmountText;
    private javax.swing.JTextField totalDeductionText;
    private javax.swing.JTextField totalEarningsText;
    private javax.swing.JButton viewButton;
    private javax.swing.JComboBox yearIDCombo;
    // End of variables declaration//GEN-END:variables
    private void viewSalaryDetails() throws ParseException, SQLException, ClassNotFoundException{
        //Earnings=============================================================
        SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat yearFormat=new SimpleDateFormat("yyyy");
        String employeeID=employeeIDCombo.getSelectedItem().toString();
        lastDay=getLastDate();
        Calendar c=Calendar.getInstance();
        c.setTime(dateFormat.parse(lastDay));
        c.add(Calendar.MONTH, -1);
        c.add(Calendar.DATE, 1);
        lastMonthLastDay=dateFormat.format(c.getTime());
        String OTRate=null;
        ResultSet rst1=EmployeeController.getAllEmployees_GradeDetails(employeeID);
        while(rst1.next()){
            basicSalaryText.setText(rst1.getString("basicSalary"));
            OTRate=rst1.getString("OTRate");
        }

        int OTHourCount=AttendanceController.getOTHourCount(employeeID, lastMonthLastDay, lastDay);
        otAmountText.setText(Double.toString(Double.parseDouble(OTRate)*OTHourCount));

        if("".equals(bonusAmountText.getText())){
            totalEarningsText.setText(Double.toString(Double.parseDouble(basicSalaryText.getText())+Double.parseDouble(otAmountText.getText())));
        }else{
            totalEarningsText.setText(Double.toString(Double.parseDouble(basicSalaryText.getText())+Double.parseDouble(otAmountText.getText())+Double.parseDouble(bonusAmountText.getText())));
        }

        epfEmployerText.setText(Double.toString(Double.parseDouble(basicSalaryText.getText())*0.15));
        etfEmployerText.setText(Double.toString(Double.parseDouble(basicSalaryText.getText())*0.03));


        //Deductions==================================================================
        epfEmployeeText.setText(Double.toString(Double.parseDouble(basicSalaryText.getText())*0.10));
        SalaryAdvance salaryAdvance=PaymentController.searchSalaryAdvanceDetail(employeeID, lastMonthLastDay, lastDay);
        if(salaryAdvance==null){
            advanceSalaryText.setText("0.0");
        }else{
            advanceSalaryText.setText(Double.toString(salaryAdvance.getAmount()));
        }

        ArrayList<Loan> processingLoanList=PaymentController.searchProcessingLoan(employeeID);
        double totalLoanInstallment=0;
        for(Loan loan : processingLoanList){
            totalLoanInstallment+=loan.getMonthlyIntallment();
        }
        loanAmountText.setText(Double.toString(totalLoanInstallment));

        Employee employee=EmployeeController.searchEmployee(employeeID);
        Grade grade=GradeController.searchGrade(employee.getGradeID());
        LeaveCount leaveCountInYear=EmployeeController.getUsedLeaveCount(employeeID, yearFormat.format(new Date()));
        LeaveCount leaveCountInMonth=EmployeeController.getUsedLeaveCountInMonth(employeeID, lastMonthLastDay, lastDay);
        if(grade.getNoPayLeaveCount()>leaveCountInYear.getNoPayCount()){
            noPayAmountText.setText("0.0");
        }else{
            int usedExcessNoPayInYear=leaveCountInYear.getNoPayCount()-grade.getNoPayLeaveCount();
            int usedNoPayInMonth=leaveCountInMonth.getNoPayCount();
            double noPayCharge=0;
            if(usedExcessNoPayInYear>usedNoPayInMonth){
                noPayCharge=usedNoPayInMonth*grade.getNoPayRate();
            }else{
                noPayCharge=usedExcessNoPayInYear*grade.getNoPayRate();
            }
            noPayAmountText.setText(Double.toString(noPayCharge));
        }

        if(grade.getHalfDayCount()>leaveCountInYear.getHalfDayCount()){
            halfDayAmountText.setText("0.0");
        }else{
            int usedExcessHalfDayInYear=leaveCountInYear.getHalfDayCount()-grade.getHalfDayCount();
            int usedHalfDayInMonth=leaveCountInMonth.getHalfDayCount();
            double halfDayCharge=0;
            if(usedExcessHalfDayInYear>usedHalfDayInMonth){
                halfDayCharge=usedHalfDayInMonth*halfDayRate;
            }else{
                halfDayCharge=usedExcessHalfDayInYear*halfDayCharge;
            }
            halfDayAmountText.setText(Double.toString(halfDayCharge));
        }

        ArrayList<Damage> damageList=PaymentController.getDamages(employeeID, lastMonthLastDay, lastDay);
        double totalDamage=0;
        for(Damage damage : damageList){
            totalDamage+=damage.getDamageCost();
        }
        damagesText.setText(Double.toString(totalDamage));

        stampFeeText.setText(Double.toString(stampFee));
        taxAmountText.setText(Double.toString(taxPercentage*Double.parseDouble(basicSalaryText.getText())));

        totalDeductionText.setText(Double.toString(Double.parseDouble(epfEmployeeText.getText())+Double.parseDouble(stampFeeText.getText())+Double.parseDouble(taxAmountText.getText())+Double.parseDouble(advanceSalaryText.getText())+Double.parseDouble(loanAmountText.getText())+Double.parseDouble(noPayAmountText.getText())+Double.parseDouble(halfDayAmountText.getText())+Double.parseDouble(damagesText.getText())));

        netAmountText.setText(Double.toString(Double.parseDouble(totalEarningsText.getText())-Double.parseDouble(totalDeductionText.getText())));
    }
    
    private void fillemployeeIDCombo() throws ClassNotFoundException, SQLException{
        ArrayList<Employee> employeeList=EmployeeController.getAllEmployees();
        for(Employee employee : employeeList){
            employeeIDCombo.addItem(employee.getEmployeeID());
        }
    }
    
    private void fillYearCombo() throws ClassNotFoundException, SQLException, ParseException{
        ResultSet yearList=AttendanceController.getAllDates();
        while(yearList.next()){
            yearIDCombo.addItem(yearList.getString(1));
        }
    }
    
    private String getLastDate(){
        String date;
        if(monthNameCombo.getSelectedIndex()<9){
            date=yearIDCombo.getSelectedItem().toString()+"-"+0+(monthNameCombo.getSelectedIndex()+1)+"-"+25;
        }else{
            date=yearIDCombo.getSelectedItem().toString()+"-"+(monthNameCombo.getSelectedIndex()+1)+"-"+25;
        }
        return date;
    }
    
    public void printBonus(String bonus){
        if(b==false){
            bonusAmountText.setText(bonus);
            if(!"".equals(totalEarningsText.getText())){
            totalEarningsText.setText(Double.toString(Double.parseDouble(totalEarningsText.getText())+Double.parseDouble(bonus)));
            netAmountText.setText(Double.toString(Double.parseDouble(netAmountText.getText())+Double.parseDouble(bonus)));
            }
            saveButton.setEnabled(true);
            printButton.setEnabled(true);
            b=true;
        }
    }
    
    private void printReport() throws JRException{
        HashMap<String, Object> map = new HashMap<String, Object>();
        JasperReport compileReport = JasperCompileManager.compileReport(getClass().getResourceAsStream("SalaryPaymentReport.jrxml"));
        map.put("EmployeeID", employeeIDCombo.getSelectedItem().toString());
        map.put("EmployeeName", nameText.getText());
        map.put("Bank", bankNameText.getText());
        map.put("AccountNum", accNumberText.getText());
        map.put("Year",yearIDCombo.getSelectedItem().toString());
        map.put("Month",monthNameCombo.getSelectedItem().toString());
        map.put("PaymentType",paymentTypeCombo.getSelectedItem().toString());
        map.put("BasicSalary",basicSalaryText.getText());
        map.put("OTEarning",otAmountText.getText());
        map.put("Bonus",bonusAmountText.getText());
        map.put("EPF(Employer)",epfEmployerText.getText());
        map.put("ETF(Employer)",etfEmployerText.getText());
        map.put("EPF(Employee)",epfEmployeeText.getText());
        map.put("StampFee",stampFeeText.getText());
        map.put("Tax",taxAmountText.getText());
        map.put("SalaryAdvance",advanceSalaryText.getText());
        map.put("Loans",loanAmountText.getText());
        map.put("NoPayLeaves",noPayAmountText.getText());
        map.put("HalfDay",halfDayAmountText.getText());
        map.put("Damages",damagesText.getText());
        map.put("TotalEarning",totalEarningsText.getText());
        map.put("TotalDeduction",totalDeductionText.getText());
        map.put("NetSalary",netAmountText.getText());
        JasperPrint fillReport=JasperFillManager.fillReport(compileReport, map);
        JasperViewer.viewReport(fillReport,false);
    }

}
