/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payrollsystemnew.view.mainpage;

/**
 *
 * @author User
 */
public class ManageEmployeeCategoriesPanel extends javax.swing.JPanel {

    /**
     * Creates new form employeePanel
     */
    public ManageEmployeeCategoriesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addEmployeeButton = new javax.swing.JButton();
        searchEmployeeButton = new javax.swing.JButton();
        editEmployeeButton = new javax.swing.JButton();
        viewEmployeeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addEmployeeButton.setBackground(new java.awt.Color(0, 0, 0));
        addEmployeeButton.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        addEmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        addEmployeeButton.setText("Add Employee");
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 60));

        searchEmployeeButton.setBackground(new java.awt.Color(0, 0, 0));
        searchEmployeeButton.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        searchEmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        searchEmployeeButton.setText("Search");
        searchEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEmployeeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 60));

        editEmployeeButton.setBackground(new java.awt.Color(0, 0, 0));
        editEmployeeButton.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        editEmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        editEmployeeButton.setText("Delete/Update");
        editEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(editEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 60));

        viewEmployeeButton.setBackground(new java.awt.Color(0, 0, 0));
        viewEmployeeButton.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        viewEmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        viewEmployeeButton.setText("View");
        viewEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(viewEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystemnew/images/Background1.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void editEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeButtonActionPerformed
        MainFrameForm.form.loadEditEmployeePanel();
    }//GEN-LAST:event_editEmployeeButtonActionPerformed

    private void addEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeButtonActionPerformed
        MainFrameForm.form.loadAddEmployeePanel();
    }//GEN-LAST:event_addEmployeeButtonActionPerformed

    private void searchEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEmployeeButtonActionPerformed
        MainFrameForm.form.loadSearchEmployeePanel();
    }//GEN-LAST:event_searchEmployeeButtonActionPerformed

    private void viewEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeeButtonActionPerformed
        MainFrameForm.form.loadViewEmployeePanel();
    }//GEN-LAST:event_viewEmployeeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeButton;
    private javax.swing.JButton editEmployeeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchEmployeeButton;
    private javax.swing.JButton viewEmployeeButton;
    // End of variables declaration//GEN-END:variables
}
