/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payrollsystemnew.view.employee;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import payrollsystemnew.controller.DepartmentController;
import payrollsystemnew.controller.EmployeeController;
import payrollsystemnew.controller.GradeController;
import payrollsystemnew.controller.PaymentController;
import payrollsystemnew.model.Department;
import payrollsystemnew.model.Employee;
import payrollsystemnew.model.Grade;
import payrollsystemnew.model.PaymentType;
import payrollsystemnew.other.Validation;

/**
 *
 * @author User
 */
public class EditEmployeePanel extends javax.swing.JPanel {
    SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
    Department department;
    static String empoyeeID=null; 
    /**
     * Creates new form employeePanel
     */
    public EditEmployeePanel() {
        initComponents();
        joiningDateText.setDateFormat(dateFormat);
        dobText.setDateFormat(dateFormat);
        try {
            fillemployeeIDCombo();
            filldeparmentIDCombo();
            fillgradeIDCombo();  
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(EditEmployeePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        nicText = new javax.swing.JTextField();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        maritalStatusCombo = new javax.swing.JComboBox();
        addressText = new javax.swing.JTextField();
        contactNumText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        employeeIDCombo = new javax.swing.JComboBox();
        dobText = new org.freixas.jcalendar.JCalendarCombo();
        joiningDateText = new org.freixas.jcalendar.JCalendarCombo();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        departmentNameText = new javax.swing.JTextField();
        departmentIDCombo = new javax.swing.JComboBox();
        gradeIDCombo = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bankNameCombo = new javax.swing.JComboBox();
        accountNumberText = new javax.swing.JTextField();
        cashCheckBox = new javax.swing.JCheckBox();
        chequeCheckBox = new javax.swing.JCheckBox();
        depositCheckBox = new javax.swing.JCheckBox();
        updateButton = new javax.swing.JButton();
        deleteButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Employee ID :");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Employee Name :");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("NIC :");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Date Of Birth :");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Gender :");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Marital Status :");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Address :");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Contact Number :");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Joining Date :");

        firstNameText.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        firstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextActionPerformed(evt);
            }
        });
        firstNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                firstNameTextKeyReleased(evt);
            }
        });

        nicText.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        nicText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicTextKeyReleased(evt);
            }
        });

        maleButton.setBackground(new java.awt.Color(102, 102, 102));
        maleButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        maleButton.setForeground(new java.awt.Color(204, 204, 204));
        maleButton.setText("Male");
        maleButton.setOpaque(false);

        femaleButton.setBackground(new java.awt.Color(102, 102, 102));
        femaleButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        femaleButton.setForeground(new java.awt.Color(204, 204, 204));
        femaleButton.setText("Female");
        femaleButton.setOpaque(false);

        maritalStatusCombo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        maritalStatusCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Married" }));
        maritalStatusCombo.setSelectedIndex(-1);

        addressText.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        contactNumText.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        contactNumText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactNumTextKeyReleased(evt);
            }
        });

        lastNameText.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextActionPerformed(evt);
            }
        });
        lastNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lastNameTextKeyReleased(evt);
            }
        });

        employeeIDCombo.setEditable(true);
        employeeIDCombo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        employeeIDCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                employeeIDComboItemStateChanged(evt);
            }
        });
        employeeIDCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeIDComboActionPerformed(evt);
            }
        });

        dobText.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        joiningDateText.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(addressText)
                        .addComponent(contactNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(maleButton)
                        .addGap(18, 18, 18)
                        .addComponent(femaleButton))
                    .addComponent(employeeIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nicText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(maritalStatusCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dobText, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(joiningDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(employeeIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nicText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dobText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(maleButton)
                    .addComponent(femaleButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(maritalStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(contactNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(joiningDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 500));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Department Info.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setOpaque(false);

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Department ID :");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Department :");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Grade ID :");

        departmentNameText.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        departmentIDCombo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        departmentIDCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                departmentIDComboItemStateChanged(evt);
            }
        });

        gradeIDCombo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gradeIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(gradeIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(departmentIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(departmentNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 420, 200));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Info.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Payment Type :");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Bank :");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Account No :");

        bankNameCombo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        bankNameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Peoples' Bank", "Bank of Ceylon", "Hatton National Bank", "" }));

        accountNumberText.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        accountNumberText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                accountNumberTextKeyReleased(evt);
            }
        });

        cashCheckBox.setBackground(new java.awt.Color(102, 102, 102));
        cashCheckBox.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cashCheckBox.setForeground(new java.awt.Color(204, 204, 204));
        cashCheckBox.setText("Cash");
        cashCheckBox.setOpaque(false);

        chequeCheckBox.setBackground(new java.awt.Color(102, 102, 102));
        chequeCheckBox.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        chequeCheckBox.setForeground(new java.awt.Color(204, 204, 204));
        chequeCheckBox.setText("Cheque");
        chequeCheckBox.setOpaque(false);

        depositCheckBox.setBackground(new java.awt.Color(102, 102, 102));
        depositCheckBox.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        depositCheckBox.setForeground(new java.awt.Color(204, 204, 204));
        depositCheckBox.setText("Deposit");
        depositCheckBox.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(chequeCheckBox)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(depositCheckBox)
                                    .addComponent(cashCheckBox))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(cashCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chequeCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(depositCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bankNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 420, 300));

        updateButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, 110, -1));

        deleteButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deleteButton1.setText("Delete");
        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 530, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystemnew/images/Background.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void lastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextActionPerformed

    private void employeeIDComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_employeeIDComboItemStateChanged
        
    }//GEN-LAST:event_employeeIDComboItemStateChanged

    private void departmentIDComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_departmentIDComboItemStateChanged
        try {
            String deptID = (String)departmentIDCombo.getSelectedItem();
            Department dept = DepartmentController.searchDepartment(deptID);
            departmentNameText.setText(dept.getName());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(EditEmployeePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_departmentIDComboItemStateChanged

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String employeeID=employeeIDCombo.getSelectedItem().toString();
        String firstName=firstNameText.getText();
        String lastName=lastNameText.getText();
        String NIC=nicText.getText();
        String address=addressText.getText();
        String dateOfBirth=dateFormat.format(dobText.getDate());
        String gender=maleButton.isSelected()?"male":"female";
        String maritalStatus=maritalStatusCombo.getSelectedItem().toString();
        String contactNumber=contactNumText.getText();
        String joiningDate=dateFormat.format(joiningDateText.getDate());
        String gradeID=gradeIDCombo.getSelectedItem().toString();
        String departmentID=departmentIDCombo.getSelectedItem().toString();

        try {
            int rowCount1=EmployeeController.updateEmployee(new Employee(employeeID, firstName, lastName, NIC, address, contactNumber, dateOfBirth, gender, maritalStatus, joiningDate, gradeID, departmentID));
            int rowCount2=PaymentController.updatePaymenTypeDetail(new PaymentType(employeeID, cashCheckBox.isSelected(), chequeCheckBox.isSelected(), depositCheckBox.isSelected(), bankNameCombo.getSelectedItem().toString(), accountNumberText.getText()));
            String oldDepartmentID=department.getDepartmentID();
            String oldDepertmentName=department.getName();
            int oldEmployeeCount=department.getNumOfEmployees();
            oldEmployeeCount--;
            int rowCount3=DepartmentController.updateDepartment(new Department(oldDepartmentID, oldDepertmentName, oldEmployeeCount));
            department=DepartmentController.searchDepartment(departmentIDCombo.getSelectedItem().toString());
            String newDepartmentID=department.getDepartmentID();
            String newDepertmentName=department.getName();
            int newEmployeeCount=department.getNumOfEmployees();
            newEmployeeCount++;
            int rowCount4=DepartmentController.updateDepartment(new Department(newDepartmentID, newDepertmentName, newEmployeeCount));
            if(rowCount1>0 && rowCount2>0 && rowCount3>0 && rowCount4>0  ){
                JOptionPane.showMessageDialog(this, "Employee updated succesfully.");
            }else{
                JOptionPane.showMessageDialog(this, "Employee update failed.");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Employee update failed.");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton1ActionPerformed
        try {
            if(!PaymentController.isThereLoan(employeeIDCombo.getSelectedItem().toString())){
                int rowCount1=EmployeeController.deleteEmployee(employeeIDCombo.getSelectedItem().toString());
                String departmentID=department.getDepartmentID();
                String departmentName=department.getName();
                int employeeCount=department.getNumOfEmployees();
                employeeCount--;
                int rowCount2=DepartmentController.updateDepartment(new Department(departmentID,departmentName, employeeCount));
                int rowCount3=PaymentController.deletePaymenTypeDetail(employeeIDCombo.getSelectedItem().toString());

                if(rowCount1>0 && rowCount2>0){
                    JOptionPane.showMessageDialog(this, "Employee deleted successfully.");
                }else{
                    JOptionPane.showMessageDialog(this, "Employee deletion failed.");
                }
            }else{
                new LeaveConfirmationForm().setVisible(true);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(EditEmployeePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteButton1ActionPerformed

    private void firstNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameTextKeyReleased
        Validation.name(firstNameText);
    }//GEN-LAST:event_firstNameTextKeyReleased

    private void firstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextActionPerformed
        
    }//GEN-LAST:event_firstNameTextActionPerformed

    private void lastNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameTextKeyReleased
        Validation.name(lastNameText);
    }//GEN-LAST:event_lastNameTextKeyReleased

    private void nicTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicTextKeyReleased
        Validation.validateNIC(nicText);
    }//GEN-LAST:event_nicTextKeyReleased

    private void contactNumTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNumTextKeyReleased
        Validation.phoneNumber(contactNumText);
    }//GEN-LAST:event_contactNumTextKeyReleased

    private void accountNumberTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountNumberTextKeyReleased
        Validation.accNumber(accountNumberText);
    }//GEN-LAST:event_accountNumberTextKeyReleased

    private void employeeIDComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeIDComboActionPerformed
        try {
            empoyeeID=employeeIDCombo.getSelectedItem().toString();
            if(employeeIDCombo.getSelectedIndex()!=-1){
                Employee employee=EmployeeController.searchEmployee(employeeIDCombo.getSelectedItem().toString());
                firstNameText.setText(employee.getFirstName());
                lastNameText.setText(employee.getLastName());
                nicText.setText(employee.getNIC());
                dobText.setSelectedItem(employee.getDateOfBirth());
                if("male".equals(employee.getGender())){
                    maleButton.setSelected(true);
                }
                maritalStatusCombo.setSelectedItem(employee.getMaritalStatus());
                addressText.setText(employee.getAddress());
                contactNumText.setText(employee.getContactNumber());
                joiningDateText.setSelectedItem(employee.getJoiningDate());
                gradeIDCombo.setSelectedItem(employee.getGradeID());
                departmentIDCombo.setSelectedItem(employee.getDepartmentID());
                department = DepartmentController.searchDepartment(employee.getDepartmentID());
                departmentNameText.setText(department.getName());

                PaymentType paymentType=PaymentController.getPaymentTypesDetail(employeeIDCombo.getSelectedItem().toString());
                cashCheckBox.setSelected(paymentType.isCash());
                chequeCheckBox.setSelected(paymentType.isCheque());
                depositCheckBox.setSelected(paymentType.isDeposit());
                bankNameCombo.setSelectedItem(paymentType.getBankName());
                accountNumberText.setText(paymentType.getAccNumber());
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(EditEmployeePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_employeeIDComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNumberText;
    private javax.swing.JTextField addressText;
    private javax.swing.JComboBox bankNameCombo;
    private javax.swing.JCheckBox cashCheckBox;
    private javax.swing.JCheckBox chequeCheckBox;
    private javax.swing.JTextField contactNumText;
    private javax.swing.JButton deleteButton1;
    private javax.swing.JComboBox departmentIDCombo;
    private javax.swing.JTextField departmentNameText;
    private javax.swing.JCheckBox depositCheckBox;
    private org.freixas.jcalendar.JCalendarCombo dobText;
    private javax.swing.JComboBox employeeIDCombo;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JComboBox gradeIDCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private org.freixas.jcalendar.JCalendarCombo joiningDateText;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JComboBox maritalStatusCombo;
    private javax.swing.JTextField nicText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
    private void fillemployeeIDCombo() throws ClassNotFoundException, SQLException{
        ArrayList<Employee> employeeList=EmployeeController.getAllEmployees();
        for(Employee employee : employeeList){
            employeeIDCombo.addItem(employee.getEmployeeID());
        }
        AutoCompleteDecorator.decorate(employeeIDCombo);
    }
    
    private void filldeparmentIDCombo() throws ClassNotFoundException, SQLException{
        ArrayList<Department> departmentIDList=DepartmentController.getAllDepartments();
        for(Department dept : departmentIDList){
            departmentIDCombo.addItem(dept.getDepartmentID());
        }
    }
    
    private void fillgradeIDCombo() throws ClassNotFoundException, SQLException{
        ArrayList<Grade> gradeList=GradeController.getAllGrades();
        for(Grade grade : gradeList){
            gradeIDCombo.addItem(grade.getGradeID());
        }
    }

}
