/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payrollsystemnew.view.employee;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import payrollsystemnew.controller.EmployeeController;
import payrollsystemnew.controller.GradeController;
import payrollsystemnew.model.Employee;
import payrollsystemnew.model.Grade;
import payrollsystemnew.model.LeaveCount;
import payrollsystemnew.model.Leaves;
import payrollsystemnew.other.Validation;

/**
 *
 * @author User
 */
public class GrantLeavePanel extends javax.swing.JPanel {
    private SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
    /**
     * Creates new form employeePanel
     */
    public GrantLeavePanel() {
       initComponents();
        try {
            fillemployeeIDCombo();
            dateText.setDateFormat(dateFormat);
            leaveDateText.setDateFormat(dateFormat);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(GrantLeavePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        employeeIDCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        reasonText = new javax.swing.JTextField();
        leaveTypeCombo = new javax.swing.JComboBox();
        doneButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        numOfDaysText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        remainingHalfDayText = new javax.swing.JTextField();
        remainingNoPayText = new javax.swing.JTextField();
        remainingLeavesText = new javax.swing.JTextField();
        dateText = new org.freixas.jcalendar.JCalendarCombo();
        leaveDateText = new org.freixas.jcalendar.JCalendarCombo();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Employee ID :");

        employeeIDCombo.setEditable(true);
        employeeIDCombo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        employeeIDCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                employeeIDComboItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Name :");

        nameText.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Leave Date :");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Type :");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Reason :");

        reasonText.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        leaveTypeCombo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        leaveTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Leave", "No Pay Leave" }));

        doneButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Number of Days :");

        numOfDaysText.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        numOfDaysText.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        numOfDaysText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOfDaysTextActionPerformed(evt);
            }
        });
        numOfDaysText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numOfDaysTextFocusLost(evt);
            }
        });
        numOfDaysText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numOfDaysTextKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Date :");

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Leaves Left (for this year) :");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Leave     :");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("No Pay   :");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Half Day :");

        remainingHalfDayText.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        remainingHalfDayText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remainingHalfDayTextActionPerformed(evt);
            }
        });

        remainingNoPayText.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        remainingLeavesText.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(remainingNoPayText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(remainingLeavesText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(remainingHalfDayText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(remainingLeavesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(remainingNoPayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(remainingHalfDayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dateText.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        leaveDateText.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leaveDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(employeeIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(206, 206, 206)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reasonText, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leaveTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numOfDaysText, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(employeeIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(leaveDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(numOfDaysText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(leaveTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(reasonText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56)
                .addComponent(doneButton)
                .addGap(75, 75, 75))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystemnew/images/Background.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void employeeIDComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_employeeIDComboItemStateChanged
        if(employeeIDCombo.getSelectedIndex()!=-1){
            try {
                Employee employee=EmployeeController.searchEmployee(employeeIDCombo.getSelectedItem().toString());
                nameText.setText(employee.getFirstName()+" "+employee.getLastName());

                Grade grade=GradeController.searchGrade(employee.getGradeID());
                SimpleDateFormat yearFormat=new SimpleDateFormat("yyyy");
                String year=yearFormat.format(dateText.getDate());
                LeaveCount leaveCount=EmployeeController.getUsedLeaveCount(employeeIDCombo.getSelectedItem().toString(), year);
                remainingLeavesText.setText(Integer.toString(grade.getLeavesCount()-leaveCount.getHalfDayCount()/2));
                remainingHalfDayText.setText(Integer.toString(grade.getHalfDayCount()-leaveCount.getHalfDayCount()));
                remainingNoPayText.setText(Integer.toString(grade.getNoPayLeaveCount()-leaveCount.getNoPayCount()));
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(GrantLeavePanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_employeeIDComboItemStateChanged

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        String employeeID=employeeIDCombo.getSelectedItem().toString();
        String leaveType=leaveTypeCombo.getSelectedItem().toString();
        Date startingDate=leaveDateText.getDate();
        int numOfDays=Integer.parseInt(numOfDaysText.getText());
        String reason=reasonText.getText();

        String leaveDate=dateFormat.format(startingDate);
        Calendar c = Calendar.getInstance();
        c.setTime(startingDate);
        int[] rowCount=new int[numOfDays];
        
            for(int i=0;i<numOfDays;i++){
                try {
                    rowCount[i]=EmployeeController.addLeaveDetail(new Leaves(employeeID, leaveDate, leaveType, reason));
                    c.add(Calendar.DATE, 1);
                    leaveDate=dateFormat.format(c.getTime());
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(GrantLeavePanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            int totalRowCount=0;
            for(int i=0;i<numOfDays;i++){
                totalRowCount+=rowCount[i];
            }
            if(totalRowCount==numOfDays){
            try {
                JOptionPane.showMessageDialog(this, "Leave added successfully.");
                Employee employee=EmployeeController.searchEmployee(employeeIDCombo.getSelectedItem().toString());
                Grade grade=GradeController.searchGrade(employee.getGradeID());
                SimpleDateFormat yearFormat=new SimpleDateFormat("yyyy");
                String year=yearFormat.format(dateText.getDate());
                LeaveCount leaveCount=EmployeeController.getUsedLeaveCount(employeeIDCombo.getSelectedItem().toString(), year);
                remainingLeavesText.setText(Integer.toString(grade.getLeavesCount()-leaveCount.getHalfDayCount()/2));
                remainingHalfDayText.setText(Integer.toString(grade.getHalfDayCount()-leaveCount.getHalfDayCount()));
                remainingNoPayText.setText(Integer.toString(grade.getNoPayLeaveCount()-leaveCount.getNoPayCount()));
                numOfDaysText.setText("");
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(GrantLeavePanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else{
                JOptionPane.showMessageDialog(this, "Leave addition failed.");
            }
        
    }//GEN-LAST:event_doneButtonActionPerformed

    private void numOfDaysTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOfDaysTextActionPerformed
         
    }//GEN-LAST:event_numOfDaysTextActionPerformed

    private void numOfDaysTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numOfDaysTextFocusLost
       
    }//GEN-LAST:event_numOfDaysTextFocusLost

    private void remainingHalfDayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remainingHalfDayTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remainingHalfDayTextActionPerformed

    private void numOfDaysTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numOfDaysTextKeyReleased
        Validation.twoIntegers(numOfDaysText);
        if(!"".equals(numOfDaysText.getText())){
            if(leaveTypeCombo.getSelectedItem().toString().equals("Leave")){
                if(Integer.parseInt(numOfDaysText.getText())>Integer.parseInt(remainingLeavesText.getText())){
                    JOptionPane.showMessageDialog(this, "Number exceeding the remaining amount.");
                    numOfDaysText.setText("");
                    numOfDaysText.requestFocus();
                }
            }
            if(leaveTypeCombo.getSelectedItem().toString().equals("No Pay Leave")){
                if(Integer.parseInt(numOfDaysText.getText())>Integer.parseInt(remainingNoPayText.getText())){
                    JOptionPane.showMessageDialog(this, "Number exceeding the remaining amount.");
                    numOfDaysText.setText("");
                    numOfDaysText.requestFocus();
                }
            }
            if(leaveTypeCombo.getSelectedItem().toString().equals("Half Day Leave")){
                if(Integer.parseInt(numOfDaysText.getText())>Integer.parseInt(remainingHalfDayText.getText())){
                    JOptionPane.showMessageDialog(this, "Number exceeding the remaining amount.");
                    numOfDaysText.setText("");
                    numOfDaysText.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_numOfDaysTextKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.freixas.jcalendar.JCalendarCombo dateText;
    private javax.swing.JButton doneButton;
    private javax.swing.JComboBox employeeIDCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private org.freixas.jcalendar.JCalendarCombo leaveDateText;
    private javax.swing.JComboBox leaveTypeCombo;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField numOfDaysText;
    private javax.swing.JTextField reasonText;
    private javax.swing.JTextField remainingHalfDayText;
    private javax.swing.JTextField remainingLeavesText;
    private javax.swing.JTextField remainingNoPayText;
    // End of variables declaration//GEN-END:variables
     private void fillemployeeIDCombo() throws ClassNotFoundException, SQLException{
        ArrayList<Employee> employeeList=EmployeeController.getAllEmployees();
        for(Employee employee : employeeList){
            employeeIDCombo.addItem(employee.getEmployeeID());
        }
        AutoCompleteDecorator.decorate(employeeIDCombo);
    }

}
