/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payrollsystemnew.view.employee;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
import payrollsystemnew.controller.AttendanceController;
import payrollsystemnew.controller.DepartmentController;
import payrollsystemnew.controller.EmployeeController;
import payrollsystemnew.model.Department;
import payrollsystemnew.model.Employee;

/**
 *
 * @author User
 */
public class VeiwAttendaceViaDatePanel extends javax.swing.JPanel {
    private SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
    private DefaultTableModel tableModel;
    /**
     * Creates new form employeePanel
     */
    public VeiwAttendaceViaDatePanel() {
        initComponents();
        try {
            tableModel=(DefaultTableModel) attendenceTable.getModel();
            filldeparmentCombos();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VeiwAttendaceViaDatePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        dateText.setDateFormat(dateFormat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attendenceTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        departmentNameCombo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        dateText = new org.freixas.jcalendar.JCalendarCombo();
        proceedButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attendenceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Name", "In Time", "Short Leave Out Time", "Short Leave In Time", "Out Time", "OT Hours"
            }
        ));
        jScrollPane1.setViewportView(attendenceTable);
        if (attendenceTable.getColumnModel().getColumnCount() > 0) {
            attendenceTable.getColumnModel().getColumn(0).setPreferredWidth(25);
            attendenceTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            attendenceTable.getColumnModel().getColumn(2).setPreferredWidth(30);
            attendenceTable.getColumnModel().getColumn(3).setPreferredWidth(50);
            attendenceTable.getColumnModel().getColumn(4).setPreferredWidth(50);
            attendenceTable.getColumnModel().getColumn(5).setPreferredWidth(25);
            attendenceTable.getColumnModel().getColumn(6).setPreferredWidth(15);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 800, 370));

        jPanel2.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Department :");

        departmentNameCombo.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Date :");

        dateText.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        proceedButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        proceedButton.setText("Proceed");
        proceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(proceedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(departmentNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(333, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(departmentNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proceedButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 900, 100));

        printButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        jPanel1.add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystemnew/images/Background.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButtonActionPerformed
        try {
            SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
            String deptName=departmentNameCombo.getSelectedItem().toString();
            String date=dateFormat.format(dateText.getDate());
            tableModel=(DefaultTableModel) attendenceTable.getModel();
            
            tableModel.setRowCount(0);
            ResultSet rst=AttendanceController.viewAttendaceViaDate(deptName, date);
            while(rst.next()){
                Employee employee=EmployeeController.searchEmployee(rst.getString(1));
                Object[] rowData={rst.getString(1),employee.getFirstName()+" "+employee.getLastName(),rst.getString(3),(rst.getString(4)!=null)?rst.getString(4):"-",(rst.getString(5)!=null)?rst.getString(5):"-",rst.getString(6),rst.getString(7)};
                tableModel.addRow(rowData);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(VeiwAttendaceViaDatePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }//GEN-LAST:event_proceedButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        printAttendanceTable();
    }//GEN-LAST:event_printButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable attendenceTable;
    private org.freixas.jcalendar.JCalendarCombo dateText;
    private javax.swing.JComboBox departmentNameCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printButton;
    private javax.swing.JButton proceedButton;
    // End of variables declaration//GEN-END:variables
     private void filldeparmentCombos() throws ClassNotFoundException, SQLException{
        ArrayList<Department> departmentIDList=DepartmentController.getAllDepartments();
        for(Department dept : departmentIDList){
            departmentNameCombo.addItem(dept.getName());
        }
    }
     
     private void printAttendanceTable(){
        HashMap<String,Object> map=new HashMap<String,Object>();
        JRTableModelDataSource dataSource=new JRTableModelDataSource(tableModel);   
        try {
            JasperReport compileReport=JasperCompileManager.compileReport(getClass().getResourceAsStream("AttendanceViaDateReport.jrxml"));
            map.put("Department", departmentNameCombo.getSelectedItem().toString());
            map.put("Date", dateFormat.format(dateText.getDate()));
            JasperPrint fillReport=JasperFillManager.fillReport(compileReport, map, dataSource);
            JasperViewer.viewReport(fillReport,false);
        } catch (JRException ex) {
            Logger.getLogger(ViewEmployeeViaDeptPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
