/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payrollsystemnew.view.employee;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import payrollsystemnew.controller.EmployeeController;
import payrollsystemnew.model.Employee;

/**
 *
 * @author User
 */
public class ViewEmployeePanel extends javax.swing.JPanel {
    
    /**
     * Creates new form employeePanel
     */
    public ViewEmployeePanel() {
        initComponents();
        try {
            ArrayList<Employee> employeeList=EmployeeController.getAllEmployees();
            DefaultTableModel dtm=(DefaultTableModel) employeeTable.getModel();
            dtm.setRowCount(0);
            for(Employee emp:employeeList){
                Object[] rowData={emp.getEmployeeID(),emp.getFirstName(),emp.getLastName(),emp.getNIC(),emp.getAddress(),emp.getDateOfBirth(),emp.getGender(),emp.getMaritalStatus(),emp.getContactNumber(),emp.getJoiningDate(),emp.getGradeID(),emp.getDepartmentID()};
                dtm.addRow(rowData);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewEmployeePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp ID", "First Name", "Last Name", "NIC", "Address", "DOB", "Gender", "Marital Status", "Contatc No.", "Joined Date", "Grade", "Dept.ID"
            }
        ));
        employeeTable.setOpaque(false);
        jScrollPane1.setViewportView(employeeTable);
        if (employeeTable.getColumnModel().getColumnCount() > 0) {
            employeeTable.getColumnModel().getColumn(0).setPreferredWidth(45);
            employeeTable.getColumnModel().getColumn(1).setPreferredWidth(65);
            employeeTable.getColumnModel().getColumn(2).setPreferredWidth(80);
            employeeTable.getColumnModel().getColumn(4).setPreferredWidth(55);
            employeeTable.getColumnModel().getColumn(6).setPreferredWidth(50);
            employeeTable.getColumnModel().getColumn(9).setPreferredWidth(70);
            employeeTable.getColumnModel().getColumn(10).setPreferredWidth(45);
            employeeTable.getColumnModel().getColumn(11).setPreferredWidth(45);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 880, 520));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payrollsystemnew/images/Background.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable employeeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    

}
